sandbox_mode = "danger-full-access"
model = "gpt-5.4"
model_reasoning_effort = "medium"
reasoning = "xhigh"
network_access = "enabled"
personality = "pragmatic"
approval_policy = "on-request"
check_for_update_on_startup = true
web_search = "live"
plan_mode_reasoning_effort = "xhigh"

[defaults]
network = true
trust_level = "trusted"

[sandbox_workspace_write]
network_access = true

[features]
unified_exec = true
shell_snapshot = true
steer = true
collaboration_modes = true

[mcp_servers.honeycomb]
url = "https://mcp.honeycomb.io/mcp"

[mcp_servers.pagerduty]
url = "https://mcp.pagerduty.com/mcp"

[mcp_servers.pagerduty.env_http_headers]
Authorization = "PAGERDUTY_AUTHORIZATION"

[mcp_servers.elasticsearch]
command = "npx"
args = ["-y", "@elastic/mcp-server-elasticsearch"]

[mcp_servers.elasticsearch.env]
ES_API_KEY = "${ES_API_KEY}"
ES_URL = "${ES_URL}"

[mcp_servers.notion]
url = "https://mcp.notion.com/mcp"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.http_headers]
CONTEXT7_API_KEY = "${CONTEXT7_API_KEY}"

[mcp_servers.openmemory]
command = "npx"
args = ["-y", "supergateway", "--sse", "http://localhost:8765/mcp/openmemory/sse/tj"]

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[notice.model_migrations]
"gpt-5.2" = "gpt-5.3-codex"
