language: generic

env:
  global:
    - CURL=curl -fsSkL --retry 9 --retry-delay 9
  matrix:
#    - EMACS=emacs AKA=emacs23
    - EMACS=emacs24
#    - EMACS=emacs-snapshot
# matrix:
#   allow_failures:
#     - env: EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask install
  - which cask
  - cask --version
install:
  - if test $EMACS = emacs; then
      $CURL https://raw.githubusercontent.com/ohler/ert/fb3c278d/lisp/emacs-lisp/ert.el -o ert.el;
      $CURL http://elpa.gnu.org/packages/cl-lib-0.5.el -o cl-lib.el;
    fi
script:
  - make test
notifications:
  email: false
