- hosts: localhost
  tasks:
    - name: install packages
      become: yes
      package:
        name:
          - google-chrome
          - zsh
          - redshift
          - emacs
          - docker
          - docker-compose
          - tilix
        state: present    
    - name: install goenv
      become: no
      git:
        repo: https://github.com/syndbg/goenv.git
        version: master
        dest: "{{ ansible_env.HOME }}/.goenv"
        accept_hostkey: yes
      #   - name: install dotflies
      # become: yes
      # - name: install goenv
      # become: yes
      # package:
      #   name: goenv
      #   state: present
