apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: homelab
  labels:
    app.kubernetes.io/name: adguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adguard
    spec:
      hostNetwork: true
      containers:
        - name: adguard-home
          ports:
            - containerPort: 3000
          image: adguard/adguardhome
          volumeMounts:
            - mountPath: /opt/adguardhome/conf
              name: config
            - mountPath: /opt/adguardhome/work
              name: work
      volumes:
        - name: config
          hostPath:
            path: /home/tj/.local/adguard/config
        - name: work
          hostPath:
            path: /home/tj/.local/adguard/work
---
apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: homelab
  labels:
    app.kubernetes.io/name: adguard
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/name: adguard
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-ingress
  namespace: homelab
  annotations:
    isskubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "lets-encrypt-issuer"
spec:
  tls:
    - secretName: haus-travisjeffery-com-tls
      hosts:
        - '*.haus.travisjeffery.com'
  rules:
    - host: adguard.haus.travisjeffery.com
      http:
        paths:
          - path: /
            backend:
              serviceName: adguard
              servicePort: 80
          
    - host: plex.haus.travisjeffery.com
      http:
        paths:
          - path: /
            backend:
              serviceName: plex
              servicePort: 80
    - host: deluge.haus.travisjeffery.com
      http:
        paths:
          - path: /
            backend:
              serviceName: deluge
              servicePort: 80
    - host: syncthing.haus.travisjeffery.com
      http:
        paths:
          - path: /
            backend:
              serviceName: syncthing
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: homelab
  labels:
    app.kubernetes.io/name: plex
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
    spec:
      hostNetwork: true
      containers:
        - name: plex
          image: linuxserver/plex
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: VERSION
              value: "docker"
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /tv
              name: tv
            - mountPath: /movies
              name: movies
      volumes:
        - name: config
          hostPath:
            path: /mnt/data/Plex
        - name: tv
          hostPath:
            path: /mnt/data/Television
        - name: movies
          hostPath:
            path: /mnt/data/Movies
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: homelab
  labels:
    app.kubernetes.io/name: plex
spec:
  ports:
    - port: 80
      targetPort: 32400
  selector:
    app.kubernetes.io/name: plex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: homelab
  labels:
    app.kubernetes.io/name: deluge
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: deluge
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deluge
    spec:
      hostNetwork: true
      containers:
        - name: deluge
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/deluge
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
      volumes:
        - name: config
          hostPath:
            path: /home/tj/.config/deluge
        - name: downloads
          hostPath:
            path: /mnt/data
---
apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: homelab
  labels:
    app.kubernetes.io/name: deluge
spec:
  ports:
    - port: 80
      targetPort: 8112
  selector:
    app.kubernetes.io/name: deluge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: homelab
  labels:
    app.kubernetes.io/name: syncthing
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: syncthing
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: syncthing
    spec:
      hostNetwork: true
      containers:
        - name: syncthing
          ports:
            - containerPort: 8384
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/syncthing
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          hostPath:
            path: /mnt/data/Sync
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: homelab
  labels:
    app.kubernetes.io/name: syncthing
spec:
  ports:
    - port: 80
      targetPort: 8384
  selector:
    app.kubernetes.io/name: syncthing
