- name: current user
  debug: msg="{{ lookup('env','USER') }}"
- name: home dir
  debug: msg="{{ ansible_env.HOME }}"
- name: playbook dir
  debug: msg="{{ playbook_dir }}"
- name: make zsh default shell
  shell: chsh -s /bin/zsh tj
  tags: shellchange
  become: true
- name: start docker service
  service:
    name: docker
    state: started
  become: true
- name: clone goenv
  git:
    repo: https://github.com/syndbg/goenv.git
    version: master
    dest: "{{ ansible_env.HOME }}/.goenv"
    accept_hostkey: yes
- name: find dotfiles
  find:
    paths: "{{ playbook_dir }}"
    hidden: true
  register: dotfiles
- name: install dotfiles
  file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path | basename }}"
    state: link
    force: true
  with_items: "{{ dotfiles.files }}"
- name: find org files
  find:
    paths: "{{ sync_dir }}"
    hidden: true
    patterns:
      - "*.org"
  register: orgfiles
  when: sync_dir != ""
- name: install orgfiles
  file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path | basename }}"
    state: link
    force: true
  with_items: "{{ orgfiles.files }}"
  when: sync_dir != ""
- name: symlink draft dir
  file:
    src: "{{ sync_dir }}/Notes/Draft"
    dest: "{{ ansible_env.HOME }}/draft"
    state: link
    force: true
  when: sync_dir != ""
- name: find homedir symlinks
  find:
    paths: "{{ sync_dir }}"
    hidden: true
    file_type: any
    excludes:
      - ".stfolder"
  register: homedirs
  when: sync_dir != ""
- name: install homedir symlinks
  file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path | basename }}"
    state: link
    force: true
  with_items: "{{ homedirs.files }}"
  when: sync_dir != ""
